apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: core
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Core applications of my cluster
  # Allow manifests to deploy from any Git repos
  sourceRepos:
  - '*'
  destinations: 
  - namespace: '*'
    server: https://kubernetes.default.svc