apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: adguardhome
  name: adguardhome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguardhome
  strategy: {}
  template:
    metadata:
      labels:
        app: adguardhome
    spec:
      containers:
      - image: adguard/adguardhome:v0.107.61
        name: adguardhome
        ports:
        - containerPort: 80
          name: web
        - containerPort: 53
          name: dns
          protocol: UDP
        volumeMounts:
        - name: {{ .Values.storage.pvc.work.volumeName }}
          mountPath: /opt/adguardhome/work
        - name: {{ .Values.storage.pvc.conf.volumeName }}
          mountPath: /opt/adguardhome/conf
        resources: {}
      volumes:
      - name: {{ .Values.storage.pvc.work.volumeName }}
        persistentVolumeClaim:
          claimName: {{ .Values.storage.pvc.work.name }}
      - name: {{ .Values.storage.pvc.conf.volumeName }}
        persistentVolumeClaim:
          claimName: {{ .Values.storage.pvc.conf.name }}
status: {}
