apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: homemade
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: https://github.com/iliesbenyahia/jarvis-apps
      revision: HEAD
      directories:
      - path: apps/homemade/*
  template:
    metadata:
      name: '{{.path.basename}}'
    spec:
      project: "homemade"
      source:
        repoURL: https://github.com/iliesbenyahia/{{.path.basename}}.git
        targetRevision: HEAD
        path: 'helm'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{.path.basename}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
